services:
  nats:
    image: nats:2.10-alpine
    container_name: oasis-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: >
      -js
      -m 8222
      --tls
      --tlscert=/etc/nats/certs/nats-server.pem
      --tlskey=/etc/nats/certs/nats-server-key.pem
      --tlscacert=/etc/nats/certs/nats-ca.pem
      --tlsverify
    volumes:
      - ././certs:/etc/nats/certs:ro
      - ././data/nats:/data
    restart: unless-stopped
