services:
  nats:
    image: nats:2.11-alpine
    container_name: nats-tls
    env_file:
      - .env
    command:
      - "nats-server"
      - "--config"
      - "/etc/nats/nats-server.conf"
      - "--jetstream"
    ports:
      - "4443:4443"
      - "8222:8222"
    volumes:
      - ./certs:/etc/nats/certs:ro
      - ./jwt:/etc/nats/jwt:ro
      - ./certs/nats-server.conf:/etc/nats/nats-server.conf:ro
      - nats-data:/data/nats
    restart: unless-stopped

volumes:
  nats-data: {}
