# Oasis 系统配置文件

[telemetry]
log_level = "info"
log_format = "text"
log_no_ansi = false

[nats]
url = "tls://127.0.0.1:4222"

[grpc]
url = "https://localhost:50051"

[tls]
certs_dir = "./certs"

[server]
listen_addr = "0.0.0.0:50051"
heartbeat_ttl_sec = 60
