[agent]
# agent_id = "my-unique-agent-id"

[nats]
url = "tls://localhost:4443"
# NATS 连接配置(证书)
creds_file = "certs/nats.creds"
tls_ca_file = "certs/nats-ca.pem"
tls_cert_file = "certs/nats-client.pem"
tls_key_file = "certs/nats-client-key.pem"

[executor]
command_timeout_sec = 300

[security]
# audit_log_path = "/var/log/oasis-agent-audit.log"

enforce_whitelist = true
[whitelist]
paths = ["/bin/", "/usr/bin/"]


[telemetry]
# 日志级别: trace, debug, info, warn, error
log_level = "info"
# 日志格式: text, json
log_format = "text"
log_no_ansi = false


groups = ["blue", "batch-1"]

[labels]
environment = "production"
region = "cn-shanghai"
