[package]
name = "oasis-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tonic = { workspace = true }
oasis-core = { path = "../oasis-core" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
indicatif = "0.17"
which = "6.0"
toml = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt-multi-thread",
  "fs",
  "process",
] }
console = "0.15"
comfy-table = "7.1"
rcgen = "0.12"
chrono = "0.4"
