[package]
name = "oasis-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "oasis-cli"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tonic = { workspace = true }
oasis-core = { path = "../oasis-core" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sysinfo = { workspace = true }
humantime = "2.1"
which = "6.0"
toml = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt-multi-thread",
  "fs",
  "process",
  "io-std",
] }
console = "0.15"
comfy-table = "7.1"
rcgen = "0.12"
chrono = "0.4"
time = "0.3"
futures = "0.3"
bytesize = "1.3"
